[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
asyncio_default_test_loop_scope = function

addopts = -v -s --slowmo 1000
markers =
    smoke: маркировка для смоук тестов
    regress: маркировка для регрессионных тестов
    auth: маркировка позволяет использоватать файл состояния авторизации auth_state.json

;testpaths =

filterwarnings =
    ignore::DeprecationWarning